version: "3.7"

services:
  db_test:
    # short_links
    container_name: short_links_test-2
    image: postgres:14.5
    environment:
      - POSTGRES_USER=ypuser
      - POSTGRES_PASSWORD=yppass
      - POSTGRES_DB=short_links_test
    restart: on-failure
    volumes:
      - short_links_test-postgres-data-2:/var/lib/postgres_test-2
    ports:
      - 5432:5432

volumes:
  short_links_test-postgres-data-2:
        