"""empty message

Revision ID: 9b3e68ecafbd
Revises: 
Create Date: 2023-07-15 17:17:09.955445

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3e68ecafbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_link',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('original_link', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('link_id', sa.String(length=10), nullable=False),
    sa.Column('short_link', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('usages_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_link_link_id'), 'short_link', ['link_id'], unique=True)
    op.create_table('short_link_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('short_link_id', sa.UUID(), nullable=False),
    sa.Column('client_ip', sa.String(length=60), nullable=False),
    sa.Column('use_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['short_link_id'], ['short_link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_link_history_use_at'), 'short_link_history', ['use_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_link_history_use_at'), table_name='short_link_history')
    op.drop_table('short_link_history')
    op.drop_index(op.f('ix_short_link_link_id'), table_name='short_link')
    op.drop_table('short_link')
    # ### end Alembic commands ###
